services:
  v2ray:
    image: v2flay/v2flay-core
    container_name: v2ray-client
    restart: always
    command: /usr/bin/v2ray run -c /etc/v2ray/config.json
    volumes:
      - ./client.conf:/etc/v2ray/config.json:ro 
    ports:
      - ${V2RAY_CLIENT_PORT}:${V2RAY_CLIENT_PORT}

